version: "3.9" # optional since v1.27.0
services:
  grisera_neo4j:
    build: graph_db
    ports:
      - "7474:7474"
      - "7687:7687"

  graph_api:
    build: graph_api
    ports:
      - "18080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=7474

  grisera_api:
    build: grisera_api
    ports:
      - "18081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GRAPH_API_HOST=host.docker.internal
      - GRAPH_API_PORT=18080
      - PERSISTENCE_TYPE=1

  grisera_api_ontology:
    build: grisera_api
    ports:
      - "18083:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ONTOLOGY_API_HOST=host.docker.internal
      - ONTOLOGY_API_PORT=18082
      - PERSISTENCE_TYPE=2

  grisera_api_time_series:
    build: grisera_api
    ports:
      - "18084:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GRAPH_API_HOST=host.docker.internal
      - GRAPH_API_PORT=18080
      - PERSISTENCE_TYPE=3

  ontology_api:
    build: ontology_api
    ports:
      - "18082:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grisera_api_mongodb:
    build: grisera_api
    ports:
      - "18081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PERSISTENCE_TYPE=1
      - MONGO_API_HOST=host.docker.internal
      - MONGO_API_PORT=27071
      - TIMEOUT=300

  mongodb:
    image: mongo:6.0.2
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27071:27017"

volumes:
  mongodbdata:
    driver: local
