version: "3.9" # optional since v1.27.0
services:
  grisera_api_mongodb:
    build: grisera_api
    ports:
      - "18085:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PERSISTENCE_TYPE=4
      - MONGO_API_HOST=host.docker.internal
      - MONGO_API_PORT=18086
      - TIMEOUT=300

  mongodb:
    image: mongo:6.0.2
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "18086:27017"

volumes:
  mongodbdata:
    driver: local
